**Encoding Categorical Data**

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

: 

In [113]:
df=pd.read_csv('customer.csv',usecols=['review','education','purchased'])

In [114]:
#convert colum into lower case
df['review']=df['review'].str.lower()
df['education']=df['education'].str.lower()
df['purchased']=df['purchased'].str.lower()

only input and output columns of data

In [115]:
df.head()

,purchased,review,education
0,yes,good,ug
1,yes,poor,school
2,yes,poor,ug
3,yes,excellent,ug
4,yes,average,school


In [116]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['review','education']],df['purchased'],test_size=0.2,random_state=42)

x_train before encoding

In [117]:
x_train

,review,education
249,excellent,pg
433,average,pg
19,excellent,school
322,excellent,pg
332,good,ug
...,...,...
106,average,ug
270,good,pg
348,excellent,pg
435,good,pg


y_train before encoding

In [118]:
y_train

249     no
433    yes
19      no
322    yes
332    yes
      ... 
106    yes
270    yes
348    yes
435     no
102     no
Name: purchased, Length: 400, dtype: object

**ordinal encoding of input columns**

In [119]:
from sklearn.preprocessing import OrdinalEncoder

In [120]:
oe= OrdinalEncoder(categories=[['poor','average','good','excellent'],['school','ug','pg']])

**fit on only train data but transform on both train and test data**

In [121]:
oe.fit(x_train)

OrdinalEncoder(categories=[['poor', 'average', 'good', 'excellent'],
                           ['school', 'ug', 'pg']])

In [122]:
x_train=oe.transform(x_train)
x_test=oe.transform(x_test)

x_train after encoding

In [123]:
x_train


array([[3., 2.],
       [1., 2.],
       [3., 0.],
       [3., 2.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [3., 2.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [3., 2.],
       [0., 2.],
       [2., 0.],
       [3., 0.],
       [2., 1.],
       [0., 0.],
       [3., 2.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [3., 0.],
       [1., 2.],
       [0., 0.],
       [3., 0.],
       [1., 2.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [3., 2.],
       [0., 0.],
       [0., 0.],
       [3., 1.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [3., 2.],
       [3., 1.],
       [1., 1.],
       [3., 1.],
       [3., 0.],
       [0., 2.

**Label Encoding for output colum**

In [124]:
from sklearn.preprocessing import LabelEncoder

In [125]:
le= LabelEncoder()

In [126]:
le.fit(y_train)

LabelEncoder()

In [127]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

y_train after encoding

In [128]:
y_train

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,

y_test After encoding

In [129]:
y_test


array([0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0])